# ~/.config/kitty/kitty.conf

# Include a theme if desired:
# include ~/.config/kitty/themes/my-theme.conf

# Window
background_opacity 0.85
remember_window_size  no
initial_window_width  1280
initial_window_height 800

# Font
font_family      Monaspace Neon NF
bold_font        Monaspace Neon NF Bold
italic_font      Monaspace Neon NF Italic
bold_italic_font Monaspace Neon NF Italic
font_size        12.0

# Primary colors
background #1A1D23
foreground #ffffff

# Normal colors
color0  #111317
color1  #FF838B
color2  #87C05F
color3  #DFAB25
color4  #5EB7FF
color5  #DD97F1
color6  #4AC2B8
# color7 #ffffff

# Bright colors
color8  #34363A
color9  #FFA6AE
color10 #AAE382
color11 #FFCE48
color12 #81DAFF
color13 #FFBAFF
color14 #6DE5DB
color15 #ffffff

# Indexed colors
color16 #EB8332
color17 #F8747E

