# Location
# ~/.config/kitty/kitty.conf

# Theme Location
include ~/.config/kitty/themes/Atom.conf

# Window
background_opacity 0.85
remember_window_size  no
initial_window_width  1280
initial_window_height 800
resize_debounce_time 0.0

# Font
font_family      Monaspace Neon NF
bold_font        Monaspace Neon NF Bold
italic_font      Monaspace Neon NF Italic
bold_italic_font Monaspace Neon NF Italic
font_size        12.0


