background            #1A1D23
foreground            #ADB0BB
cursor                #5EB7FF

selection_background  #26343F
selection_foreground  #ADB0BB

color0                #111317
color1                #F8747E
color2                #75AD47
color3                #D09214
color4                #50A4E9
color5                #CC83E3
color6                #00B298
color7                #9B9FA9

color8                #3A3E47
color9                #FF838B
color10               #87C05F
color11               #DFAB25
color12               #5EB7FF
color13               #DD97F1
color14               #4AC2B8
color15               #ADB0BB