background            #1A1D23
foreground            #9B9FA9
cursor                #ADB0BB
selection_background  #26343F
selection_foreground  #1A1D23

color0                #111317
color8                #5E626B

color1                #FF838B
color9                #FFB7BD

color2                #87C05F
color10               #C0E69E

color3                #DFAB25
color11               #F4D67A

color4                #5EB7FF
color12               #A8D9FF

color5                #DD97F1
color13               #F1C5FA

color6                #4AC2B8
color14               #8BE0D9

color7                #9B9FA9
color15               #ADB0BB